const metadata = {
  title: process.env.NEXT_PUBLIC_SITE_NAME,
  description: process.env.NEXT_PUBLIC_SITE_DESCRIPTION,
  keywords: [
    process.env.NEXT_PUBLIC_SITE_NAME,
    'c++',
    'css',
    'developers london ontario',
    'fanshawe college',
    'front-end developer',
    'front-end development',
    'html',
    'javascript',
    'next.js',
    'personal portfolio',
    'react',
    'software developer',
    'software development',
    'tailwind',
    'tailwindcss',
    'typescript',
    'university of western ontario',
    'web design',
    'web designer',
    'web developer',
    'web developers canada',
    'web developers london ontario',
    'web developers london',
    'web developers ontario',
    'web developers',
    'web development',
    'western university',
  ],
};

export default metadata;
